---
title: "Welcome"
engine: knitr
sidebar: main
---

::: {.mwadd}
(MW) 

## Feedback

This is coming along very nicely!! And I think it might be managable to compress everything in 2-3 afternoons.

I have added feedback to each of the episodes in these orange boxes.

-- Martijn

### Some other feedback not added to episodes

(**TO DO:** Add this from notes.)

:::

Welcome to the RNA-seq workshop of the bioDSC. This workshop will introduce you to the basics of gene expression analysis using RNA-Seq. It is going to be fun and empowering! You will discover how the total RNA pool of an organism is converted to short sequences called “reads” that can in turn be used to get insights into gene expression. Through careful experimental design, this gene expression information can answer research questions and offer biological insights.

The workshop consists of two core parts: 

1. **Bioinformatics:** Quality control of the reads, mapping reads to a reference genome, and count the number of reads per gene. This will give us a count table!
2. **Differential gene expression:** We will use DESeq2 to discover differentially expressed genes in certain conditions. DESeq2 will use your count table as input.

The materials on this website are meant to be discussed in two four-hour trainer-led workshop sessions. However, it should also be possible to follow the materials on your own, at your own pace. Regardless of how you go through the materials, we hope that you will learn something useful!

## Learning objectives

After this workshop, you should be able to:

- Identify good practices when designing a RNA-Seq experiment
- Assess the quality of RNA-seq sequencing data (“reads”) using the command-line instructions
- Align RNA-seq reads to a reference genome using a splice-aware aligner (e.g. STAR).
- Generate a count matrix from the RNA-seq data alignment
- Perform a QC of your experiment through Principal Component Analysis (PCA) and sample clustering.
- Execute a differential gene expression analysis using R and the DESeq2 package.
- Be able to create key plots: volcano plot, heatmap and clustering of differentially expressed genes.


## Schedule

insert table here

::: {.mwadd}

*Trying to estimate times for each parts.*

| Day    | Episode                                            | Duration   | Time       |
|--------|----------------------------------------------------|------------|------------|
| Day 1  | Experimental considerations                        | 30 min     | 13:00      |
| Day 1  | From FASTQ to count table -- code along            | 60 min     | 13:30      |
| Day 1  | Break                                              | 30 min     | 14:30      |
| Day 1  | From FASTQ to count table -- code yourself         | 90 min     | 15:00      |
| Day 1  | (end)                                              | /          | 16:30      |

| Day    | Episode                                            | Duration   | Time       |
|--------|----------------------------------------------------|------------|------------|
| Day 1  | Differential expression analysis -- code along     | 60 min     | 13:00      |
| Day 1  | Differential expression analysis -- code yourself  | 90 min     | 13:00      |
| Day 1  | Break                                              | 30 min     | 14:30      |
| Day 1  | Enrichment analysis -- lecture                     | 30 min     | 15:00      |
| Day 1  | Enrichment analysis -- code yourself               | 30 min     | 15:00      |
| Day 1  | (end)                                              | /          | 17:00      |

Perhaps make this also three afternoons??
The second day seems awefully tight..

:::


## Maintainers

Current maintainers of this workshop page are members of the [bioDSC (University of Amsterdam)](https://www.biodsc.nl).

## Credits

This workshop is based on other teaching materials available online. The primary source is the [RNA-seq lesson designed by the Science Park Study Group](https://scienceparkstudygroup.github.io/rna-seq-lesson/), which in turn was based on [Harvard Chan Bioinformatics Core RNA-seq materials](https://hbctraining.github.io/Intro-to-bulk-RNAseq/schedule/links-to-lessons.html).